apiVersion: v2
name: kube-system
description: Kubernetes system chart responsible for internal applications like monitoring
type: application
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 34.6.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus-statsd-exporter
    version: 0.4.2
    repository: https://prometheus-community.github.io/helm-charts